-- Create "encounters" Table

CREATE TABLE "encounters" (
	"Id"	TEXT,
	"START"	TEXT,
	"STOP"	TEXT,
	"PATIENT"	TEXT,
	"ORGANIZATION"	TEXT,
	"PAYER"	TEXT,
	"ENCOUNTERCLASS"	TEXT,
	"CODE"	INTEGER,
	"DESCRIPTION"	TEXT,
	"BASE_ENCOUNTER_COST"	REAL,
	"TOTAL_CLAIM_COST"	REAL,
	"PAYER_COVERAGE"	REAL,
	"REASONCODE"	NUMERIC,
	"REASONDESCRIPTION"	TEXT
)

-- Create "patients" Table

CREATE TABLE "patients" (
	"Id"	TEXT,
	"BIRTHDATE"	TEXT,
	"DEATHDATE"	TEXT,
	"PREFIX"	TEXT,
	"FIRST"	TEXT,
	"LAST"	TEXT,
	"SUFFIX"	TEXT,
	"MAIDEN"	TEXT,
	"MARITAL"	TEXT,
	"RACE"	TEXT,
	"ETHNICITY"	TEXT,
	"GENDER"	TEXT,
	"BIRTHPLACE"	TEXT,
	"ADDRESS"	TEXT,
	"CITY"	TEXT,
	"STATE"	TEXT,
	"COUNTY"	TEXT,
	"ZIP"	INTEGER,
	"LAT"	REAL,
	"LON"	REAL
)

-- Create "payers" Table

CREATE TABLE "payers" (
	"Id"	TEXT,
	"NAME"	TEXT,
	"ADDRESS"	TEXT,
	"CITY"	TEXT,
	"STATE_HEADQUARTERED"	TEXT,
	"ZIP"	TEXT,
	"PHONE"	TEXT
)

-- Create "procedures" Table

CREATE TABLE "procedures" (
	"START"	TEXT,
	"STOP"	TEXT,
	"PATIENT"	TEXT,
	"ENCOUNTER"	TEXT,
	"CODE"	INTEGER,
	"DESCRIPTION"	TEXT,
	"BASE_COST"	INTEGER,
	"REASONCODE"	INTEGER,
	"REASONDESCRIPTION"	TEXT
)
